const express = require('express');
const { Client, LocalAuth } = require('whatsapp-web.js');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(express.json({ limit: '20mb' }));

const TZ = 'Africa/Johannesburg';
const WEEKLY_TARGET = Number(process.env.WEEKLY_REVENUE_TARGET || process.env.MONTHLY_REVENUE_TARGET || 96154);
const ANNUAL_TARGET = Number(process.env.ANNUAL_REVENUE_TARGET || 5000000);
const SESSION_DIR = '/app/.wwebjs_auth';

const client = new Client({
  authStrategy: new LocalAuth({ dataPath: SESSION_DIR, clientId: 'btsa-finance' }),
  puppeteer: { headless: true, executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium', args: ['--no-sandbox', '--disable-setuid-sandbox'] },
});
let latestQr = null;
function fmtMoney(v) { return `R${Math.round(Number(v || 0)).toLocaleString('en-ZA')}`; }
function localDateParts(date = new Date()) { const parts = new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date); const out={}; for(const p of parts) if(p.type!=='literal') out[p.type]=p.value; return {year:Number(out.year),month:Number(out.month),day:Number(out.day)}; }
function parseTxnDate(value){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d;}
function startOfLocalDay(date=new Date()){const p=localDateParts(date);return new Date(`${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}T00:00:00+02:00`);}
function mondayStart(date=new Date()){const d=startOfLocalDay(date);const localDay=d.getDay();const diff=localDay===0?6:localDay-1;d.setDate(d.getDate()-diff);return d;}
function daysBetweenLocal(from,to){return Math.max(0,Math.floor((startOfLocalDay(to)-startOfLocalDay(from))/86400000));}

function summarizeInvoices(invoices,now=new Date()){
 const clean=invoices.map(x=>({id:x.Id||x.id,txnDate:parseTxnDate(x.TxnDate||x.txnDate),total:Number(x.TotalAmt??x.total??0),balance:Number(x.Balance??x.balance??0),privateNote:String(x.PrivateNote||x.privateNote||'')})).filter(x=>x.txnDate&&x.total>=0&&!/voided/i.test(x.privateNote));
 const weekStart=mondayStart(now); const prevWeekStart=new Date(weekStart);prevWeekStart.setDate(prevWeekStart.getDate()-7); const prevWeekEnd=new Date(weekStart); const p=localDateParts(now); const monthStart=new Date(`${p.year}-${String(p.month).padStart(2,'0')}-01T00:00:00+02:00`);
 const thisWeek=clean.filter(x=>x.txnDate>=weekStart&&x.txnDate<=now); const prevWeek=clean.filter(x=>x.txnDate>=prevWeekStart&&x.txnDate<prevWeekEnd); const mtd=clean.filter(x=>x.txnDate>=monthStart&&x.txnDate<=now); const sum=a=>a.reduce((n,x)=>n+x.total,0);
 const thisWeekRevenue=sum(thisWeek),prevWeekRevenue=sum(prevWeek),mtdRevenue=sum(mtd),thisWeekAvg=thisWeek.length?thisWeekRevenue/thisWeek.length:0,prevWeekAvg=prevWeek.length?prevWeekRevenue/prevWeek.length:0;
 const outstanding=clean.filter(x=>x.balance>0);const buckets={current:{count:0,value:0},d2to7:{count:0,value:0},d7to10:{count:0,value:0},d10plus:{count:0,value:0}};for(const x of outstanding){const age=daysBetweenLocal(x.txnDate,now);const b=age<=1?buckets.current:age<=7?buckets.d2to7:age<=10?buckets.d7to10:buckets.d10plus;b.count++;b.value+=x.balance;}
 const totalOutstanding=outstanding.reduce((a,b)=>a+b.balance,0); const targetPct=WEEKLY_TARGET?(thisWeekRevenue/WEEKLY_TARGET)*100:0; const weeklyChangePct=prevWeekRevenue?((thisWeekRevenue-prevWeekRevenue)/prevWeekRevenue)*100:null; const avgChangePct=prevWeekAvg?((thisWeekAvg-prevWeekAvg)/prevWeekAvg)*100:null; const mtdOutstanding=mtd.reduce((a,b)=>a+Math.min(b.balance,b.total),0); const unpaidPct=mtdRevenue?(mtdOutstanding/mtdRevenue)*100:0;
 const warnings=[]; if(thisWeekRevenue<WEEKLY_TARGET){const behind=((WEEKLY_TARGET-thisWeekRevenue)/WEEKLY_TARGET)*100;warnings.push(`This week is ${behind.toFixed(0)}% behind the ${fmtMoney(WEEKLY_TARGET)} weekly target.`);} if(weeklyChangePct!==null&&weeklyChangePct<=-10)warnings.push(`Weekly sales dropped ${Math.abs(weeklyChangePct).toFixed(0)}% versus last week.`); if(avgChangePct!==null&&avgChangePct<=-10)warnings.push(`Average invoice value fell from ${fmtMoney(prevWeekAvg)} to ${fmtMoney(thisWeekAvg)}.`); if(mtdRevenue>0&&unpaidPct>=20)warnings.push(`${unpaidPct.toFixed(0)}% of MTD invoiced revenue remains unpaid.`);
 let summary;if(thisWeekRevenue<WEEKLY_TARGET&&weeklyChangePct!==null&&weeklyChangePct<0)summary=`Weekly revenue is below the pace required for the ${fmtMoney(ANNUAL_TARGET)} annual target and is down on last week. Focus is closing the weekly revenue gap while preventing older debtors from growing.`;else if(thisWeekRevenue<WEEKLY_TARGET)summary=`Weekly revenue is below the ${fmtMoney(WEEKLY_TARGET)} target required to support the ${fmtMoney(ANNUAL_TARGET)} annual goal. Debtor ageing should be watched alongside the sales gap.`;else summary=`Weekly revenue is at or above target. The main finance risk to watch is movement in overdue debtors and average invoice value.`;
 return {thisWeekRevenue,prevWeekRevenue,weeklyChangePct,mtdRevenue,targetPct,thisWeekCount:thisWeek.length,thisWeekAvg,prevWeekAvg,buckets,totalOutstanding,warnings,summary};
}
function renderReport(s){const change=s.weeklyChangePct===null?'n/a':`${s.weeklyChangePct>=0?'+':''}${s.weeklyChangePct.toFixed(0)}%`;const lines=['*BTSA Weekly Revenue Report*','','*Revenue Position*',`This week: ${fmtMoney(s.thisWeekRevenue)}`,`Month-to-date: ${fmtMoney(s.mtdRevenue)}`,`Weekly target: ${fmtMoney(WEEKLY_TARGET)}`,`Weekly target achieved: ${s.targetPct.toFixed(0)}%`,`Annual revenue goal: ${fmtMoney(ANNUAL_TARGET)}`,'','*Revenue Trend*',`This week: ${fmtMoney(s.thisWeekRevenue)}`,`Previous week: ${fmtMoney(s.prevWeekRevenue)}`,`Change: ${change}`,`Invoices this week: ${s.thisWeekCount}`,`Average invoice value: ${fmtMoney(s.thisWeekAvg)}`,'','*Outstanding Invoices / Debtors*',`Current / new: ${s.buckets.current.count} | ${fmtMoney(s.buckets.current.value)}`,`2–7 days: ${s.buckets.d2to7.count} | ${fmtMoney(s.buckets.d2to7.value)}`,`7–10 days: ${s.buckets.d7to10.count} | ${fmtMoney(s.buckets.d7to10.value)}`,`10+ days: ${s.buckets.d10plus.count} | ${fmtMoney(s.buckets.d10plus.value)}`,`Total outstanding: ${fmtMoney(s.totalOutstanding)}`];if(s.warnings.length){lines.push('','*Warnings*');s.warnings.forEach(w=>lines.push(`• ${w}`));}lines.push('','*Management Summary*',s.summary);return lines.join('\n');}
app.get('/health',(req,res)=>res.json({ok:true,whatsappReady:Boolean(client.info),weeklyTarget:WEEKLY_TARGET,annualTarget:ANNUAL_TARGET}));
app.get('/qr',(req,res)=>{if(!latestQr)return res.send("<html><body><h2>Waiting for WhatsApp QR...</h2></body></html>");res.send(`<!DOCTYPE html><html><head><script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script></head><body><div id="qrcode"></div><script>new QRCode(document.getElementById('qrcode'),{text:${JSON.stringify(latestQr)},width:320,height:320});</script></body></html>`);});
app.get('/groups',async(req,res)=>{try{if(!client.info)return res.status(503).json({error:'WhatsApp not ready'});const chats=await client.getChats();res.json({groups:chats.filter(c=>c.isGroup).map(c=>({id:c.id?._serialized,name:c.name}))});}catch(e){res.status(500).json({error:e.message});}});
app.post('/report',async(req,res)=>{try{const invoices=Array.isArray(req.body)?req.body:(req.body?.invoices||[]);if(!Array.isArray(invoices))return res.status(400).json({error:'invoices array required'});const summary=summarizeInvoices(invoices,new Date());const text=renderReport(summary);const chatId=process.env.FINANCE_GROUP_ID;if(chatId){if(!client.info)return res.status(503).json({error:'WhatsApp not ready',report:text});const sent=await client.sendMessage(chatId,text);return res.json({success:true,sent:true,chatId,messageId:sent?.id?._serialized||null,report:text,summary});}res.json({success:true,sent:false,reason:'FINANCE_GROUP_ID not set',report:text,summary});}catch(e){console.error('Report error:',e);res.status(500).json({error:e.message||String(e)});}});
client.on('qr',qr=>{latestQr=qr;console.log('New WhatsApp QR generated. Open /qr to scan it.');});client.on('authenticated',()=>{latestQr=null;console.log('Finance WhatsApp authenticated.');});client.on('ready',()=>console.log('BTSA Finance WhatsApp is ready.'));client.on('auth_failure',m=>console.error('Finance WhatsApp auth failure:',m));client.on('disconnected',r=>console.log('Finance WhatsApp disconnected:',r));client.on('message',async message=>{try{if(message.fromMe)return;if(message.from?.endsWith('@g.us')){const chat=await message.getChat().catch(()=>null);console.log('FINANCE GROUP DETECTED:',message.from,chat?.name||'unknown');}}catch(e){console.error(e);}});
function removeChromiumLocks(dir){if(!fs.existsSync(dir))return;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())removeChromiumLocks(full);else if(['SingletonLock','SingletonSocket','SingletonCookie'].includes(entry.name)){try{fs.unlinkSync(full);}catch(_){}}}}removeChromiumLocks(SESSION_DIR);client.initialize();const PORT=Number(process.env.PORT||4000);app.listen(PORT,()=>console.log(`BTSA Finance WhatsApp listening on ${PORT}`));
